### ISSUE TITLE
Disable "Closing PHP tag must be on a line by itself"

### ISSUE THREAD

**Issue by ghost** [Pilot-in/PilotIn-Coding-Standards#2]
Do you prefer this

![image](https://user-images.githubusercontent.com/62112531/84036449-83896280-a99d-11ea-9a27-9cb5dcaeeb11.png)

or this?

![image](https://user-images.githubusercontent.com/62112531/84036476-8be19d80-a99d-11ea-9777-8d617b5966b5.png)

Vote for 1️⃣ or 2️⃣

**Comment by maelys-pilotin** [comment]
2️⃣
