### ISSUE TITLE
Should we add a rule to prevent having multiple empty lines?

### ISSUE THREAD

**Issue by ghost** [Pilot-in/PilotIn-Coding-Standards#3]
This:

```php

public function myTest() {
    debug('a thing);



    debug('another thing');
}
```

Should be this instead:

```php

public function myTest() {
    debug('a thing);

    debug('another thing');
}
```

👍 or 👎 ?

**Comment by maelys-pilotin** [comment]
I have already configured my Phpstorm that way (max 1 empty line)

**Comment by ghost** [comment]
It seems non-standard to have this rule, you have to use a customized version of a sniff: https://github.com/squizlabs/PHP_CodeSniffer/issues/851

We will let this be handled directly by IDE then
